name: build Docker container and push to Docker Hub

on:
  push:
    branches:
      - "main"
      - "add_tests_in_Postman"
    # paths:
    #   - "app/**"
    #   - "Postman_tests/**"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Install Postman CLI
        run: curl -o- "https://dl-cli.pstmn.io/install/linux64.sh" | sh
      - name: Build the Docker image
        run: docker build . --file Dockerfile --tag memento_test:latest
      - name: run Docker image
        run: docker run -p 3000:3000 -d memento_test
      - name: Run Postman API tests
        run: postman collection run "Postman_tests/Register_new_user_tests.postman_collection.json" 
      # - name: Login to Docker Hub
      #   uses: docker/login-action@v3
      #   with:
      #     username: ${{ secrets.DOCKERHUB_USERNAME }}
      #     password: ${{ secrets.DOCKERHUB_TOKEN }}
      # - name: Set up Docker Buildx
      #   uses: docker/setup-buildx-action@v3
      # - name: Build and push
      #   uses: docker/build-push-action@v5
      #   with:
      #     context: .
      #     file: ./Dockerfile
      #     push: true
      #     tags: ${{ secrets.DOCKERHUB_USERNAME }}/memento_app:latest , ${{ secrets.DOCKERHUB_USERNAME }}/memento_app:1.0.0
