name: build Docker container and run tests

on:
  push:
    branches-ignore:
      - main
    paths:
      - "app/**"
      - "Postman_tests/**"
      - "Dockerfile"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Get branch name
        id: get_branch
        run: echo "branch_name=${GITHUB_REF#refs/heads/}" >> $GITHUB_OUTPUT
      - name: Build the Docker image
        run: docker build . --file Dockerfile --tag memento_test:latest
      - name: run Docker container
        run: docker run -p 5000:5000 -d memento_test
      - uses: actions/setup-node@v4
        with:
          node-version: 'latest'
      - name: Install Newman CLI
        run: npm install -g newman
      - name: Install Newman HTML reporter
        run: npm install -g newman-reporter-htmlextra
      - name: Run Postman API tests in Newman CLI
        run: newman run "Postman_tests/Memento_application_integration_tests.postman_collection.json" -e "Postman_tests/Test_ENV.postman_environment.json" -r cli,htmlextra --reporter-htmlextra-export ./newman_test_reports/${{ steps.get_branch.outputs.branch_name }}_report.html
      - name: Upload newman html report
        uses: actions/upload-artifact@v4
        with:
          name: test_report_from_branch_${{ steps.get_branch.outputs.branch_name }}
          path: newman_test_reports