name: build Docker container and run tests

on:
  push:
    branches:
      - "!main"
    paths:
      - "app/**"
      - "Postman_tests/**"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Build the Docker image
        run: docker build . --file Dockerfile --tag memento_test:latest
      - name: run Docker container
        run: docker run -p 5000:5000 -d memento_test
      - name: Install Postman CLI
        run: curl -o- "https://dl-cli.pstmn.io/install/linux64.sh" | sh
      - name: Run Postman API tests
        run: postman collection run "Postman_tests/Memento_application_integration_tests.postman_collection.json" -e "Postman_tests/Test_ENV.postman_environment.json"
